baseurl = "https://ketevan.gallery/"
title = "Ketevan Gorgiladze"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  style = "default"
  description = "Ketevan Gorgiladze"
  copyright = "©2022 Ketevan Gorgiladze"
  sidebarAbout = [
    "I paint on canvas.",
    "Originally from Georgia, based in Berlin."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Gallery"
  url = "gallery/"
  home = true

  [[params.navlinks]]
  name = "Bio"
  url = "bio/"

  [params.social]
  email         = "gorgiladzeketevan@gmail.com"
  instagram     = "https://www.instagram.com/ketigorgiladze/"
